import factory
from app.utils import db
from app.models.client import Client

# Any Table fields that cannot be generated by factory.Faker() should be defined out here and used inside the class.
# This is a limitation on how factory-boy serializes args created in the Factory class.
# example
# fake_cohort_position = 'Vice President'


class ClientFactory(factory.alchemy.SQLAlchemyModelFactory):
    class Meta:
        model = Client
        sqlalchemy_session = db.session

    id = factory.Sequence(lambda n: n)
    # name = factory.Faker('name')
    # cohort_position = fake_cohort_position
