version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/PM-API
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu