version: '3.6'

services:
  api:
    build: .
    depends_on:
      - db
      - redis
    environment:
      APP_ENV: development
      STAGE: test
      # SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
      DATABASE_URL: postgresql://pm_admin:mypassword@db:5432/pm_db
      REDIS_URL: redis://redis:6379
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=pm_admin
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=pm_db
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    networks:
      - default
    ports:
      - "6379:6379"
    
volumes:
  postgres_data: