"""empty message

Revision ID: 017041aeb0e2
Revises: 6c62b5706785
Create Date: 2021-01-20 14:52:46.578332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "017041aeb0e2"
down_revision = "6c62b5706785"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
