"""empty message

Revision ID: 3bf61cf107f2
Revises: 5340044cdb8e
Create Date: 2021-01-15 11:53:18.378540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3bf61cf107f2"
down_revision = "5340044cdb8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("skills", sa.Column("skill_category_id", sa.Integer(), nullable=True))
    op.drop_constraint("skills_skills_category_id_fkey", "skills", type_="foreignkey")
    op.create_foreign_key(
        None, "skills", "skill_categories", ["skill_category_id"], ["id"]
    )
    op.drop_column("skills", "skills_category_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "skills",
        sa.Column(
            "skills_category_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "skills", type_="foreignkey")
    op.create_foreign_key(
        "skills_skills_category_id_fkey",
        "skills",
        "skill_categories",
        ["skills_category_id"],
        ["id"],
    )
    op.drop_column("skills", "skill_category_id")
    # ### end Alembic commands ###
