"""empty message

Revision ID: 4dbae139187c
Revises: 017041aeb0e2
Create Date: 2021-01-20 15:02:48.969632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4dbae139187c"
down_revision = "017041aeb0e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("github", sa.String(), nullable=True))
    op.add_column("users", sa.Column("linked_in", sa.String(), nullable=True))
    op.add_column("users", sa.Column("website", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "website")
    op.drop_column("users", "linked_in")
    op.drop_column("users", "github")
    # ### end Alembic commands ###
