"""empty message

Revision ID: 5326c4509bbb
Revises: 8eabbe1a6efe
Create Date: 2021-01-20 13:54:04.935720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5326c4509bbb"
down_revision = "8eabbe1a6efe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_education", sa.Column("institution_city", sa.String(), nullable=False)
    )
    op.add_column(
        "user_education", sa.Column("institution_country", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_education", "institution_country")
    op.drop_column("user_education", "institution_city")
    # ### end Alembic commands ###
