"""empty message

Revision ID: 5340044cdb8e
Revises: 5e71e985eb70
Create Date: 2021-01-15 10:42:55.831392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5340044cdb8e"
down_revision = "5e71e985eb70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("skill_categories", sa.Column("help", sa.Text(), nullable=True))
    op.add_column(
        "skill_categories", sa.Column("is_active", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "skill_categories", sa.Column("name", sa.String(length=100), nullable=False)
    )
    op.alter_column(
        "skill_categories", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.drop_column("skill_categories", "date_of_birth")
    op.drop_column("skill_categories", "gender")
    op.add_column("skills", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.alter_column("skills", "is_deleted", existing_type=sa.BOOLEAN(), nullable=True)
    op.add_column(
        "user_employment_skills",
        sa.Column("user_employment_id", sa.Integer(), nullable=True),
    )
    op.drop_constraint(
        "user_employment_skills_user_employement_id_fkey",
        "user_employment_skills",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "user_employment_skills",
        "user_employments",
        ["user_employment_id"],
        ["id"],
    )
    op.drop_column("user_employment_skills", "user_employement_id")
    op.add_column(
        "user_employments", sa.Column("is_current", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_employments", "is_current")
    op.add_column(
        "user_employment_skills",
        sa.Column(
            "user_employement_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "user_employment_skills", type_="foreignkey")
    op.create_foreign_key(
        "user_employment_skills_user_employement_id_fkey",
        "user_employment_skills",
        "user_employments",
        ["user_employement_id"],
        ["id"],
    )
    op.drop_column("user_employment_skills", "user_employment_id")
    op.alter_column("skills", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_column("skills", "is_active")
    op.add_column(
        "skill_categories",
        sa.Column(
            "gender",
            postgresql.ENUM("male", "female", name="gender"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "skill_categories",
        sa.Column("date_of_birth", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "skill_categories", "is_deleted", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("skill_categories", "name")
    op.drop_column("skill_categories", "is_active")
    op.drop_column("skill_categories", "help")
    # ### end Alembic commands ###
