"""empty message

Revision ID: 5c58eff8a0a9
Revises: d893d7e95bd5
Create Date: 2021-01-17 14:07:04.450951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c58eff8a0a9"
down_revision = "d893d7e95bd5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_skills", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user_skills", "users", ["user_id"], ["id"])
    op.add_column("users", sa.Column("profile_summary", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "profile_summary")
    op.drop_constraint(None, "user_skills", type_="foreignkey")
    op.drop_column("user_skills", "user_id")
    # ### end Alembic commands ###
