"""empty message

Revision ID: 6c62b5706785
Revises: 5326c4509bbb
Create Date: 2021-01-20 14:34:43.390314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c62b5706785"
down_revision = "5326c4509bbb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("job_title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "job_title")
    # ### end Alembic commands ###
