"""empty message

Revision ID: 8eabbe1a6efe
Revises: 8fd3f43355d4
Create Date: 2021-01-20 12:51:28.124210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8eabbe1a6efe"
down_revision = "8fd3f43355d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_education", sa.Column("accomplishments", sa.Text(), nullable=True)
    )
    op.alter_column(
        "user_employments", "accomplishments", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "user_employments",
        "institution_size",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "user_employments", "institution_url", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "user_employments", "work_summary", existing_type=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_employments", "work_summary", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "user_employments",
        "institution_url",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "user_employments",
        "institution_size",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "user_employments", "accomplishments", existing_type=sa.TEXT(), nullable=False
    )
    op.drop_column("user_education", "accomplishments")
    # ### end Alembic commands ###
