"""empty message

Revision ID: 8fd3f43355d4
Revises: 5c58eff8a0a9
Create Date: 2021-01-19 19:56:09.461609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8fd3f43355d4"
down_revision = "5c58eff8a0a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("employment_date", sa.Date(), nullable=True))
    op.add_column("users", sa.Column("experience_years", sa.Integer(), nullable=True))
    op.add_column(
        "users", sa.Column("personal_email", sa.String(length=100), nullable=True)
    )
    op.add_column("users", sa.Column("terminal_date", sa.Date(), nullable=True))
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.drop_column("users", "terminal_date")
    op.drop_column("users", "personal_email")
    op.drop_column("users", "experience_years")
    op.drop_column("users", "employment_date")
    # ### end Alembic commands ###
